### ISSUE TITLE
Any progress ?

### ISSUE THREAD

**Issue by AntoineTurmel** [Hugheth/dizgruntled-java#1]
This is not a real issue, but I was wondering if there are any progress or plans to work again on the game. Starting next week I will learn Java/J2E and might look at how to help.

Other point is I really liked this game and want also to port it to JavaScript so you can play across browsers.

**Comment by ForNeVeR** [comment]
It looks like more progress was done on [the bitbucket repository](https://bitbucket.org/pointcliki/dizgruntled/src/master/).

**Comment by Hugheth** [comment]
The project is being continued as a web-based TypeScript game, make sure to check out that when I release it

**Comment by boozook** [comment]
TypeScript. Great. But if you do it it's absolutelly awesome anyway and lang doesn't matter. ❤️‍🔥
