### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by ForNeVeR** [Hugheth/dizgruntled-java#2]
Hello! I've already askey you on bitbucket, but, just in case, will duplicate the question here.

Which license is Dizgruntled code plublished under? I would probably like to be involved in the project a little bit, but to do that, I'd like to know a license first.

Thanks for your work!

**Comment by Hugheth** [comment]
Hi ForNeVeR, this project is being continued as a web-based TypeScript version. I'll make sure to release that under a licence

**Comment by ForNeVeR** [comment]
That's a quite interesting initiative, and I am still interested in the idea. Are some sources and/or plans already available for public?
